### ISSUE TITLE
Integración contínua y estructura del repositorio

### ISSUE THREAD

**Issue by tomasBustamante** [agusfraccaro/tp2-Algo3#2]
- [ ] Falta configurar la herramienta de construcción del proyecto (por ejemplo [Maven](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html)) que se encargue de resolver las dependencias, compilar la aplicación y ejecutar todas las pruebas.

- [x] Falta configurar la herramienta de integración contínua (como por ejemplo [Travis](https://travis-ci.org) o [CircleCI](https://circleci.com/)) para que construya la aplicación por cada commit.

- [x] No debe subirse ningún archivo compilado (bytecode) al repositorio. Es decir, no debe haber ningún archivo con extensión `.class` ni ningún subdirectorio del tipo `bin`, `out` o `target`. Tampoco debe haber ningún archivo propio de algún IDE que estén usando.

Les recomiendo ver la estructura de [este repositorio](https://github.com/tomasBustamante/Pokemon) para tomar como ejemplo.

**Comment by agusfraccaro** [comment]
Cómo se configuran las herramientas que mencionaste? El archivo bin ya lo eliminé

**Comment by agusfraccaro** [comment]
Hola, borré la carpeta bin y ahora no me corren las pruebas porque dice que no encuentran las clases, hice revert a antes de borrar el bin pero solo me aparecen los .class de dos clases

**Comment by tomasBustamante** [comment]
Falta activar el repositorio en [Travis](https://travis-ci.org). Actualmente [no existe](https://travis-ci.org/tagusfraccaro/tp2-Algo3).
Más info acá: https://docs.travis-ci.com/user/tutorial/

**Comment by agusfraccaro** [comment]
https://travis-ci.com/agusfraccaro/tp2-Algo3 acá está el repo en travis :)

**Comment by agusfraccaro** [comment]
Ya agregue el archivo pom, dentro de la carpeta TP2, esta bien así?

**Comment by tomasBustamante** [comment]
- [ ] Falta agregar la dependencia con JUnit y el scope para que se ejecuten las pruebas como se muestra en [este tutorial](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html). Podés simplemente copiarlo de acá. El objetivo es que ejecutes localmente desde la consola `mvn test` y automáticamente se compile la aplicación y se corran las pruebas.

- [ ] En el archivo [.travis.yml](https://github.com/agusfraccaro/tp2-Algo3/blob/master/.travis.yml) falta agregar justamente el script con el comando que se ejecutará cada vez que se dispare un commit (en nuestro caso será `mvn test`). Fijate cómo está hecho [acá](https://github.com/tomasBustamante/Pokemon/blob/master/.travis.yml).

- [ ] No entiendo por qué tienen un subdirectorio `TP2`. No debería existir y debería estar `src` en la raíz, como está explicado [acá](https://campus.fi.uba.ar/mod/forum/discuss.php?d=80601).

- Los siguientes archivos y directorios no tienen que estar en el repositorio:
  - [ ] .classpath
  - [ ] .project
  - [ ] .settings
  - [ ] bin

**Comment by agusfraccaro** [comment]
El tema del subdirectorio, cómo puedo hacer para pasar todo lo que está ahí dentro a la raíz y borrar la carpeta?

**Comment by tomasBustamante** [comment]
Con el comando [move](https://www.gnu.org/software/coreutils/manual/html_node/mv-invocation.html) movés el contenido del subdirectorio `TP2` al direcotrio padre (asumiendo que estás parada en el directorio raíz del proyecto) y también renombrás el subdirectorio `tests` a `test` y lo ponés dentro de `src`. Finalmente con el comando [remove](https://www.gnu.org/software/coreutils/manual/html_node/rm-invocation.html#rm-invocation) borrás el subdirectorio `TP2` que te quedó vacío:
```console
$ mv TP2/* . 
$ mv tests src/test
$ rm -rf TP2
$ git add .
$ git commit -m "reestructuro repositorio"
$ git push origin master
```
También podés hacerlo mediante _drag & drop_ con el explorador de archivos gráfico que te provea tu sistema operativo.

**Comment by agusfraccaro** [comment]
Buenísimo, ahí creo que está todo bien con la estructura y las herramientas. Muchas muchas gracias por la ayuda, es todo muy nuevo pero ya le vamos a agarrar la mano.
